# Generated by Django 4.1.1 on 2022-09-13 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('sentiment', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500)),
                ('verified', models.BooleanField()),
                ('retweet', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.CharField(max_length=500)),
            ],
        ),
    ]
