# Generated by Django 3.0.8 on 2022-09-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sentiment', '0002_auto_20220920_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='candidate',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
