# Generated by Django 3.0.8 on 2022-10-11 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_sentiment', '0003_tweet_candidate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPolarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polarity', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.CharField(max_length=500)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_sentiment.Tweet')),
            ],
        ),
    ]
