# Generated by Django 3.0.8 on 2022-10-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_sentiment', '0004_twitterpolarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitterpolarity',
            name='tweet',
        ),
    ]
