# Generated by Django 3.0.8 on 2022-10-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sentiment', '0005_remove_twitterpolarity_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpolarity',
            name='polarity',
            field=models.FloatField(),
        ),
    ]
