# Generated by Django 3.0.8 on 2022-10-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_sentiment', '0006_auto_20221011_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterpolarity',
            name='sign',
            field=models.CharField(default='positive', max_length=500),
        ),
    ]
